### ISSUE TITLE
"list index out of range" error 

### ISSUE THREAD

**Issue by robredpath** [OpenDataServices/cove#1289]
![Screenshot 2020-08-11 at 11 38 43](https://user-images.githubusercontent.com/641009/89888045-3b6a0480-dbc7-11ea-93e4-a4376518ec11.png)

Example data to cause the error: [Example 360 conversion template 2019_notworkinginCove.xlsx](https://github.com/OpenDataServices/cove/files/5056408/Example.360.conversion.template.2019_notworkinginCove.xlsx)

https://sentry.io/organizations/open-data-services/issues/1546280006/?project=46181&query=is%3Aunresolved

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ["list index out of range" error](https://trello.com/c/6O8kenJg/46-list-index-out-of-range-error)

**Comment by michaelwood** [comment]
Note: worth checking openpyxl version to see if this is an issue that has been fixed upstream

**Comment by michaelwood** [comment]
In this case the error is due to a bug in the file itself, to do with saving the style information in the style XML and the subsequent indexing of the style information. The index it is trying to access is the length of the array, which as it's 0 indexed it is off-by-one.  

I've found It is possible to "fix" this by re-saving using an up to date version of libreoffice calc. 

There is a proposed fix in openpyxl that might allow this to be handled https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1457 and a discussion here https://groups.google.com/g/openpyxl-users/c/7Cexgsbh3Pk?pli=1 

Trace 
```
Traceback (most recent call last):
  File "./test_openpyxl.py", line 6, in <module>
    openpyxl.load_workbook("/tmp/Example.360.conversion.template.2019_notworkinginCove.xlsx",
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 315, in load_workbook
    reader.read()
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/reader/excel.py", line 279, in read
    apply_stylesheet(self.archive, self.wb)
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py", line 192, in apply_stylesheet
    stylesheet = Stylesheet.from_tree(node)
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py", line 102, in from_tree
    return super(Stylesheet, cls).from_tree(node)
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/descriptors/serialisable.py", line 103, in from_tree
    return cls(**attrib)
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py", line 93, in __init__
    self.named_styles = self._merge_named_styles()
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py", line 113, in _merge_named_styles
    self._expand_named_style(style)
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py", line 123, in _expand_named_style
    xf = self.cellStyleXfs[named_style.xfId]
  File "/home/michael/dev/ods/cove/.ve/lib/python3.8/site-packages/openpyxl/styles/cell_style.py", line 187, in __getitem__
    return self.xf[idx]
IndexError: list index out of range
```

**Comment by robredpath** [comment]
Moved to https://github.com/ThreeSixtyGiving/dataquality/issues/40
