### ISSUE TITLE
Deletion of data is not happening after 7 days

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/cove#406]
e.g. http://cove.opendataservices.coop/360/data/dc4366de-6143-4e51-a27e-66736e159e6d

We should also be testing for this better to avoid this regressing again.

**Comment by Bjwebb** [comment]
Checking /var/mail/cove (where the crontab log goes), `cove-dev` looks fine, but on `cove-live` and `cove-live-ocds` the deletion script is failing.

`cove-live`:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/cove/cove/cove/management/commands/expire_files.py", line 15, in handle
    shutil.rmtree(supplied_data.upload_dir())
  File "/home/cove/cove/.ve/lib/python3.4/shutil.py", line 464, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/cove/cove/.ve/lib/python3.4/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/cove/cove/.ve/lib/python3.4/shutil.py", line 420, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'flattened.xlsx'
```

`cove-live-ocds`:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/raven/contrib/django/management/__init__.py", line 41, in new_execute
    return original_func(self, *args, **kwargs)
  File "/home/cove/cove/.ve/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/cove/cove/cove/management/commands/expire_files.py", line 15, in handle
    shutil.rmtree(supplied_data.upload_dir())
  File "/home/cove/cove/.ve/lib/python3.4/shutil.py", line 455, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/cove/cove/.ve/lib/python3.4/shutil.py", line 453, in rmtree
    orig_st = os.lstat(path)
NotADirectoryError: [Errno 20] Not a directory: '/home/cove/cove/media/01c7b8ff-e828-4bc8-a36b-cbb737a53fd8/'
```

I've fixed the problem with both of these for now, but we should try to make sure it doesn't happen again. I can reproduce the OCDS problem by pasting in http://standard.open-contracting.org/latest/en/getting_started/releases_and_records/ as the file I want to validate.

We should possibly also be making sure that these emails go to an appropriate contact, instead of `cove@cove-live-ocds.default.opendataservices.uk0.bigv.io`

**Comment by Bjwebb** [comment]
I've replaced this with an issue for the [OCDS Cove behaviour](https://github.com/OpenDataServices/cove/issues/426) and one [about notifications from crontab](https://github.com/OpenDataServices/cove/issues/427).
