### ISSUE TITLE
'is not valid under any of the given schemas' validation error breaks ocds_cli

### ISSUE THREAD

**Issue by edugomez** [OpenDataServices/cove#931]
```bash
(.ve) user@pc:~/cove$ ./ocds-cli cove_ocds/fixtures/tenders_records_1_record_with_invalid_extensions.json

Traceback (most recent call last):
  File "./ocds-cli", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/eduardo/ODS/cove/.ve/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/eduardo/ODS/cove/.ve/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/eduardo/ODS/cove/.ve/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/eduardo/ODS/cove/.ve/lib/python3.5/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/eduardo/ODS/cove/cove_ocds/management/commands/ocds_cli.py", line 38, in handle
    result = ocds_json_output(self.output_dir, file, schema_version, convert, cache)
  File "/home/eduardo/ODS/cove/cove_ocds/lib/api.py", line 123, in ocds_json_output
    common_checks_ocds(context, output_dir, json_data, schema_ocds, api=True, cache=False)
  File "/home/eduardo/ODS/cove/cove_ocds/lib/api.py", line 35, in context_api_transform
    re.sub('(\[?|\s?)\"\]?', '', err) for err in error_group[0].split(',')
ValueError: too many values to unpack (expected 3)
```

**Comment by odscjames** [comment]
This now seems to work? Closing
